# Generated by Django 2.2.5 on 2020-02-03 17:59

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to=listings.models.upload_listing_image),
        ),
    ]
