# Generated by Django 2.2.5 on 2020-02-03 18:10

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200203_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to=listings.models.upload_listing_image),
        ),
    ]
