# Generated by Django 2.2.5 on 2020-02-03 18:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile/default.jpeg', upload_to=accounts.models.upload_listing_image),
        ),
    ]
