# Generated by Django 2.2.5 on 2020-01-24 16:06

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile/default.jpeg', upload_to=accounts.models.upload_profile_image),
        ),
    ]
